blank_issues_enabled: false
contact_links:
  - name: 💬 Discussions
    url: https://github.com/sunhailin-Leo/pyantv/discussions
    about: Use Discussions for questions, ideas, and general conversation
