from typing import Any, Self

class ChartMixin:
    def add_js_dependencies(self, *dependencies: str) -> Self: ...
    def add_js_funcs(self, *fns: str) -> Self: ...
    def add_js_events(self, *fns: str) -> Self: ...
    def load_javascript(self) -> Any: ...
    def use_renderer(self, renderer_type: str = ...) -> Self: ...
    def use_rough(
        self, roughness: float = ..., bowing: float = ...
    ) -> Self: ...
    def use_lottie(self, autoplay: bool = ...) -> Self: ...

class JsonRenderMixin:
    def set_json_encoder(self, encoder: Any = ...) -> Self: ...
