#!/usr/bin/env python3
"""基于 manifest 的画廊预览图生成脚本（不含启发式选择，严格按 YAML 清单执行）。"""

import argparse
import subprocess
import sys
import tempfile
from io import BytesIO
from pathlib import Path
from typing import Dict, Any, List

import yaml
from PIL import Image as PILImage, ImageDraw, ImageFont


def _load_manifest(manifest_path: Path) -> Dict[str, Any]:
    """加载并校验 manifest；校验项包括：version==1、examples 非空、每个 item 含 file + caption、
    grid.cols * grid.rows == len(examples)。

    Args:
        manifest_path: manifest YAML 文件路径

    Returns:
        解析后的 manifest 字典

    Raises:
        ValueError: manifest 格式错误或校验失败
        yaml.YAMLError: YAML 解析错误
    """
    if not manifest_path.exists():
        raise FileNotFoundError(f"Manifest file not found: {manifest_path}")

    with open(manifest_path, "r", encoding="utf-8") as f:
        manifest = yaml.safe_load(f)

    if manifest.get("version") != 1:
        raise ValueError("Manifest version must be 1")

    if "grid" not in manifest:
        raise ValueError("Manifest must contain 'grid' section")

    grid = manifest["grid"]
    required_grid_keys = [
        "cols",
        "rows",
        "thumbnail_width",
        "thumbnail_height",
        "caption_height",
        "padding",
        "background",
    ]
    for key in required_grid_keys:
        if key not in grid:
            raise ValueError(f"Grid must contain '{key}'")

    if "examples" not in manifest or not manifest["examples"]:
        raise ValueError("Manifest must contain non-empty 'examples' list")

    examples = manifest["examples"]
    for i, ex in enumerate(examples):
        if "file" not in ex:
            raise ValueError(f"Example {i} must contain 'file'")
        if "caption" not in ex:
            raise ValueError(f"Example {i} must contain 'caption'")

    if grid["cols"] * grid["rows"] != len(examples):
        raise ValueError(
            f"Grid size ({grid['cols']}x{grid['rows']} = {grid['cols'] * grid['rows']}) "
            f"must match number of examples ({len(examples)})"
        )

    return manifest


def _run_example_and_capture(
    example_py: Path,
    tmp_dir: Path,
    thumbnail_width: int,
    thumbnail_height: int,
    timeout: int,
    verbose: bool = False,
    fallback_html: Path = None,
) -> PILImage.Image:
    """运行单个示例生成 HTML，然后用 Playwright 截图并缩放为缩略图。

    实现步骤（严格）：
    1. subprocess.run 运行示例脚本，生成 HTML 到 cwd
    2. 查找 tmp_dir 下新增的 .html（多个取最新 mtime）
    3. Playwright chromium headless 加载，viewport 1200x900
    4. wait_for_load_state + wait_for_timeout（等动画结束）
    5. page.screenshot(full_page=False) 得到 PNG bytes
    6. PILImage.open 后 resize 为缩略图尺寸
    7. 返回 PIL Image 对象（调用方负责 paste 到画布）

    Args:
        example_py: 示例 Python 文件路径
        tmp_dir: 临时工作目录
        thumbnail_width: 缩略图宽度
        thumbnail_height: 缩略图高度
        timeout: 超时时间（秒）
        verbose: 是否输出详细日志
        fallback_html: 回退 HTML 文件路径（当运行失败时使用）

    Returns:
        缩放后的 PIL Image 对象

    Raises:
        RuntimeError: 示例运行失败或截图失败，且没有回退 HTML 文件
    """
    if verbose:
        print(f"  Running {example_py.name}...")

    html_file = None
    use_fallback = False

    try:
        subprocess.run(
            [sys.executable, str(example_py)],
            cwd=tmp_dir,
            check=True,
            timeout=timeout,
            capture_output=True,
        )
    except subprocess.TimeoutExpired:
        if fallback_html and fallback_html.exists():
            if verbose:
                print(f"  Timeout, using fallback HTML: {fallback_html.name}")
            html_file = fallback_html
            use_fallback = True
        else:
            raise RuntimeError(f"Timeout running {example_py.name} after {timeout}s")
    except subprocess.CalledProcessError as e:
        if fallback_html and fallback_html.exists():
            if verbose:
                print(f"  Failed to run, using fallback HTML: {fallback_html.name}")
            html_file = fallback_html
            use_fallback = True
        else:
            stderr_msg = e.stderr.decode('utf-8', errors='ignore')
            raise RuntimeError(
                f"Failed to run {example_py.name}: {stderr_msg}"
            )

    if not use_fallback:
        if verbose:
            print(f"  Finding HTML file in {tmp_dir}...")

        html_files = list(tmp_dir.glob("*.html"))
        if not html_files:
            if fallback_html and fallback_html.exists():
                if verbose:
                    print(
                        f"  No HTML generated, using fallback HTML: {fallback_html.name}"
                    )
                html_file = fallback_html
            else:
                raise RuntimeError(f"No HTML file generated by {example_py.name}")
        else:
            html_file = max(html_files, key=lambda p: p.stat().st_mtime)

    if verbose:
        print(f"  Using HTML: {html_file.name}")

    try:
        from playwright.sync_api import sync_playwright

        with sync_playwright() as p:
            browser = p.chromium.launch(headless=True)
            page = browser.new_page(
                viewport={"width": 1200, "height": 900},
                device_scale_factor=1.0,
            )
            page.goto(f"file://{html_file}")
            page.wait_for_load_state("networkidle", timeout=30000)
            page.wait_for_timeout(1500)
            screenshot_bytes = page.screenshot(full_page=False)
            browser.close()

        img = PILImage.open(BytesIO(screenshot_bytes))
        img = img.resize((thumbnail_width, thumbnail_height), PILImage.LANCZOS)
        return img

    except ImportError:
        raise RuntimeError(
            "Playwright not installed. Run: "
            "pip install playwright && "
            "playwright install chromium"
        )
    except Exception as e:
        raise RuntimeError(f"Failed to capture screenshot: {e}")


def _compose_grid(
    thumbnails: List[PILImage.Image],
    captions: List[str],
    grid_cols: int,
    grid_rows: int,
    thumbnail_width: int,
    thumbnail_height: int,
    caption_height: int,
    padding: int,
    background: str,
) -> PILImage.Image:
    """将缩略图 + caption 拼成网格画布。

    Args:
        thumbnails: 缩略图列表
        captions: 标题列表
        grid_cols: 网格列数
        grid_rows: 网格行数
        thumbnail_width: 缩略图宽度
        thumbnail_height: 缩略图高度
        caption_height: 标题高度
        padding: 内边距
        background: 背景色（十六进制，如 "#ffffff"）

    Returns:
        组合后的 PIL Image
    """
    canvas_width = grid_cols * thumbnail_width + (grid_cols + 1) * padding
    canvas_height = (
        grid_rows * (thumbnail_height + caption_height) + (grid_rows + 1) * padding
    )

    canvas = PILImage.new("RGB", (canvas_width, canvas_height), background)
    draw = ImageDraw.Draw(canvas)

    try:
        font = ImageFont.truetype("DejaVuSans.ttf", 14)
    except (OSError, IOError):
        font = ImageFont.load_default()

    for idx, (thumb, caption) in enumerate(zip(thumbnails, captions)):
        col = idx % grid_cols
        row = idx // grid_cols

        x = padding + col * (thumbnail_width + padding)
        y = padding + row * (thumbnail_height + caption_height + padding)

        canvas.paste(thumb, (x, y))

        text_x = x + thumbnail_width // 2
        text_y = y + thumbnail_height + 4
        draw.text((text_x, text_y), caption, fill="#333", font=font, anchor="mt")

    return canvas


def generate_gallery_preview(
    manifest_path: Path,
    examples_dir: Path,
    output_path: Path,
    timeout_per_example: int = 60,
    verbose: bool = False,
) -> None:
    """按 manifest 生成画廊预览图。

    Args:
        manifest_path: scripts/gallery_preview_manifest.yaml 的路径
        examples_dir: example/ 目录路径
        output_path: 输出 PNG 路径（docs/assets/gallery_preview.png）
        timeout_per_example: 每个示例的超时时间（秒）
        verbose: 是否输出详细日志

    Raises:
        FileNotFoundError: manifest 中列出的示例文件不存在
        RuntimeError: Playwright 截图失败，或示例脚本运行失败
        yaml.YAMLError: manifest 格式错误
    """
    manifest = _load_manifest(manifest_path)

    grid = manifest["grid"]
    examples = manifest["examples"]

    thumbnails = []
    captions = []
    failures = []

    with tempfile.TemporaryDirectory() as tmp_dir:
        tmp_path = Path(tmp_dir)

        for ex in examples:
            example_file = examples_dir / ex["file"]
            if not example_file.exists():
                error_msg = f"Example file not found: {example_file}"
                failures.append((ex["file"], error_msg))
                if verbose:
                    print(f"  ERROR: {error_msg}")
                continue

            fallback_html = (
                examples_dir / example_file.stem / (example_file.stem + ".html")
            )
            if not fallback_html.exists():
                fallback_html = examples_dir / (example_file.stem + ".html")

            try:
                thumb = _run_example_and_capture(
                    example_file,
                    tmp_path,
                    grid["thumbnail_width"],
                    grid["thumbnail_height"],
                    timeout_per_example,
                    verbose,
                    fallback_html if fallback_html.exists() else None,
                )
                thumbnails.append(thumb)
                captions.append(ex["caption"])
                if verbose:
                    print(f"  SUCCESS: {ex['file']}")
            except Exception as e:
                error_msg = f"{ex['file']}: {e}"
                failures.append((ex["file"], error_msg))
                if verbose:
                    print(f"  FAILED: {error_msg}")

    if len(thumbnails) == 0:
        raise RuntimeError("All examples failed to generate thumbnails")

    if failures:
        print(f"\nWarning: {len(failures)} example(s) failed:")
        for file, error in failures:
            print(f"  - {file}: {error}")

    canvas = _compose_grid(
        thumbnails,
        captions,
        grid["cols"],
        grid["rows"],
        grid["thumbnail_width"],
        grid["thumbnail_height"],
        grid["caption_height"],
        grid["padding"],
        grid["background"],
    )

    output_path.parent.mkdir(parents=True, exist_ok=True)
    canvas.save(output_path, "PNG")
    if verbose:
        print(f"\nSaved gallery preview to: {output_path}")


def main():
    """主函数，解析命令行参数并执行生成。"""
    parser = argparse.ArgumentParser(
        description="Generate gallery preview image from manifest"
    )
    parser.add_argument(
        "--manifest",
        type=Path,
        default=Path(__file__).parent / "gallery_preview_manifest.yaml",
        help="Path to manifest YAML file "
             "(default: scripts/gallery_preview_manifest.yaml)",
    )
    parser.add_argument(
        "--examples",
        type=Path,
        default=Path(__file__).parent.parent / "example",
        help="Path to examples directory (default: example/)",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path(__file__).parent.parent / "docs" / "assets" / "gallery_preview.png",
        help="Output PNG path (default: docs/assets/gallery_preview.png)",
    )
    parser.add_argument(
        "--timeout-per-example",
        type=int,
        default=60,
        help="Timeout for each example in seconds (default: 60)",
    )
    parser.add_argument("--verbose", action="store_true", help="Enable verbose output")

    args = parser.parse_args()

    try:
        generate_gallery_preview(
            manifest_path=args.manifest,
            examples_dir=args.examples,
            output_path=args.output,
            timeout_per_example=args.timeout_per_example,
            verbose=args.verbose,
        )
    except KeyboardInterrupt:
        print("\nInterrupted by user")
        sys.exit(1)
    except Exception as e:
        print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
